# Generated by Django 4.2.8 on 2023-12-20 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, null=True, unique=True, verbose_name='Логин пользователя')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('status', models.CharField(choices=[('выполнена', 'Выполнена'), ('не выполнена', 'Не выполнена')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('completed', models.CharField(choices=[('в работе', 'В работе'), ('запланирована', 'Запланирована'), ('завершена', 'Завершена')], max_length=20)),
                ('aim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.aim')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.category')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('task_user_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.taskuserrelation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='related_tasks',
            field=models.ManyToManyField(related_name='users', through='taskmanager.TaskUserRelation', to='taskmanager.task'),
        ),
    ]
